export const UPLOAD_PRODUCT = "UPLOAD_PRODUCT"
export const PRODUCT_UPLOADING = "PRODUCT_UPLOADING"
export const PRODUCT_UPLOAD_ERROR = "PRODUCT_UPLOAD_ERROR"
export const PRODUCT_UPLOADED = "PRODUCT_UPLOADED"